theme: minima
title: "Teymarr Page"
theme: minima
plugins:
  - jekyll-seo-tag

# Add custom CSS file (correct location outside of plugins)
sass:
  load_paths:
    - "/assets/css/custom.css"


