
theme: jekyll-theme-tactile
title: My Portfolio
description: "Welcome"
url: "https://username.github.io"  # Replace with your actual URL
# _config.yml
sass:
  style: compressed
minima:
  skin: dark

