# Site Settings
title: "Welcome"
title_separator: "-"
subtitle: "Cybersecurity Professional & Portfolio"
description: "This portfolio highlights my skills, projects, and certifications as a cybersecurity professional."
name: "Teymarr"
locale: "en-US"
baseurl: ""  # Leave empty for root directory

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Social Media Links
github_username: "TeymarrP"
linkedin_username: "teymmarpage"

# Pagination
paginate: 5

# Jekyll Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM

# Permalinks
permalink: /:year/:month/:day/:title/

# Exclude Files
exclude:
  - README.md

# Include Directories
include:
  - _pages/

# GitHub Metadata
github:
  username: "TeymarrP"
  repository: "TeymarrP"
  branch: "main"
